apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightrag-rabbitmq-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lightrag-rabbitmq-consumer
  template:
    metadata:
      labels:
        app: lightrag-rabbitmq-consumer
    spec:
      containers:
      - name: lightrag-rabbitmq-consumer
        image: lightrag-rabbitmq-consumer:latest
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: host
        - name: RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: port
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: password
        - name: RABBITMQ_QUEUE
          value: "lightrag_queue"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: api_key
      restartPolicy: Always
