apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightrag-api
  namespace: default
  labels:
    app: lightrag-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lightrag-api
  template:
    metadata:
      labels:
        app: lightrag-api
    spec:
      containers:
      - name: lightrag-api
        image: localhost:32000/lightrag-api:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: RUNTIME_ENV
          value: production
        
        # Configurations RabbitMQ
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: host
        - name: RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: port
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: password
        
        # Configurations des bases de données
        - name: MONGODB_HOST
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: host
        - name: MONGODB_PORT
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: port
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: password
        
        - name: NEO4J_HOST
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: host
        - name: NEO4J_PORT
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: port
        - name: NEO4J_USER
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: username
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: password
        
        - name: MILVUS_HOST
          valueFrom:
            secretKeyRef:
              name: milvus-credentials
              key: host
        - name: MILVUS_PORT
          valueFrom:
            secretKeyRef:
              name: milvus-credentials
              key: port
        
        # Configuration OpenAI
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: api_key
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: lightrag-api-service
  labels:
    app: lightrag-api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: lightrag-api
